export const ClientEvents = {
  HIT: 'HIT',
  STAND: 'STAND',
  BET: 'BET',
  INCREASE_BET: 'INCREASE_BET',
  DECREASE_BET: 'DECREASE_BET',
  JOIN_GAME: 'JOIN_GAME',
};

export const ServerEvents = {
  BUST: 'BUST',
  STAND: 'STAND',
  BLACKJACK: 'BLACKJACK',
  WIN: 'WIN',
  LOSE: 'LOSE',
  DRAW: 'DRAW',
  NEW_CARD: 'NEW_CARD',
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  BET_ACCEPTED: 'BET_ACCEPTED',
  GAME_STARTED: 'GAME_STARTED',
  GAME_OVER: 'GAME_OVER',
  ERROR: 'ERROR',
};
